name: aero-ssh

services:
  postgres:
    image: postgres
    container_name: aero-ssh-postgres
    environment:
      POSTGRES_DB: aero-ssh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - aero-ssh_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  aero-ssh_postgres_data: